telegram:
  bot:
    #    не вписывайте данные, так как можете отправить в публичный репозиторий
    #    используйте переменные среды для установки значений
    username: "input your name"
    token: "input taken"
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

liquibase:
  changelog: classpath:db/migration/changelog/changelog.xml



